{{- if (include "acapy.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: {{ template "acapy.fullname" . }}
  labels:
    {{- include "acapy.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  seed: {{ required ".Values.acapy.agentSeed is required" .Values.acapy.agentSeed | b64enc | quote }}
{{- end -}}